from io import BytesIO
from ..engines.mtframework.mod_156 import Mod156

try:
    import bpy
except ImportError:
    pass

bone_mapping = {
                0:"root",
                1:"spine_lower",
                2:"spine_upper",
                3:"neck",
                4:"head",
                5:"clavicle_r",
                6:"upperarm_r",
                7:"lowerarm_r",
                8:"wrist_r",
                9:"hand_r",
                10:"clavicle_l",
                11:"upperarm_l",
                12:"lowerarm_l",
                13:"wrist_l",
                14:"hand_l",
                15:"pelvis",
                16:"thigh_r",
                17:"calf_r",
                18:"foot_r",
                19:"toe_r",
                20:"thigh_l",
                21:"calf_l",
                22:"foot_l",
                23:"toe_l",
                24:"thumb_01_r",
                25:"thumb_02_r",
                26:"thumb_03_r",
                27:"index_01_r",
                28:"index_02_r",
                29:"index_03_r",
                30:"middle_01_r",
                31:"middle_02_r",
                32:"middle_03_r",
                33:"palm_r",
                34:"ring_01_r",
                35:"ring_02_r",
                36:"ring_03_r",
                37:"pinky_01_r",
                38:"pinky_02_r",
                39:"pinly_03_r",
                40:"thumb_01_l",
                41:"thumb_02_l",
                42:"thumb_03_l",
                43:"index_01_l",
                44:"index_02_l",
                45:"index_03_l",
                46:"middle_01_l",
                47:"middle_02_l",
                48:"middle_03_l",
                49:"palm_l",
                50:"ring_01_l",
                51:"ring_02",
                52:"ring_03_l",
                53:"pinky_01_l",
                54:"pinky_02_l",
                55:"pinky_03_l",
                56:"eye_r",
                57:"eye_l",
                58:"eyelid_upper_r",
                59:"eyelid_upper_l",
                60:"jaw",
                62:"clavicle_deform_r",
                63:"elbow_r",
                64:"clavicle_deform_l",
                65:"elbow_l",
                66:"butt_cheek_r",
                67:"butt_cheel_l",
                68:"knee_r",
                69:"knee_l",
                70:"ctr_upperarm_deform_1_r",
                71:"upperarm_deform_1_r",
                72:"ctr_upperarm_deform_2_r",
                73:"upperarm_deform_2_r",
                74:"lowerarm_deform_1_r",
                75:"lowerarm_deform_2_r",
                76:"ctr_upperarm_deform_1_l",
                77:"upperarm_deform_1_l",
                78:"ctr_upperarm_deform_2_l",
                79:"upperarm_deform_2_l",
                80:"lowerarm_deform_1_l",
                81:"lowerarm_deform_2_l",
                #100:"thumb_r", # jaw in ev
                #101:"thumb_l", # lip lower corner r in ev
                102:"lip_lower_2_r",
                103:"lip_lower_1_r",
                104:"lip_lower",
                105:"lip_lower_2_l",
                106:"lip_lower_1_l",
                107:"lip_corner_l",
                #108:"ev_lip_below_lower",
                #109:"ev_chin",
                #110:"ev_lip_below_lower_r",
                #111:"ev_lip_below_lower_l",
                #112:"ev_tongue_tip",
                #113:"ev_tongue_base",
                #114:"ev_jaw_r",
                #115:"ev_double_chin",
                #116:"ev_jaw_l",
                #117:"ev_eye_r",
                #118:"ev_eye_l",
                #119:"ev_lip_upper_corner_r",
                #120:"ev_lip_upper_2_r",
                #121:"ev_lip_upper_1_r",
                #122:"ev_lip_upper",
                #123:"ev_lip_upper_1_l",
                #124:"ev_lip_upper_2_l",
                #125:"ev_lip_upper_corner_l",
                #126:"ev_lip_above_upper_r",
                #127:"ev_lip_above_upper",
                #128:"ev_lip_above_upper_l",
                #129:"ev_nostril_r",
                #130:"ev_nose_tip",
                #131:"ev_nostril_l",
                #142:"ev_nose_hump",
                #147:"ev_eyelash_lower_3_r",
                #148:"ev_eyelash_lower_2_r",
                #149:"ev_eyelash_lower_1_r",
                #165:"ev_eyebrow_3_r",
                #166:"ev_eyebrow_2_r",
                #167:"ev_eyebrow_1_r",
                #168:"ev_nose_bridge",
                #169:"ev_eyebrow_1_l",
                #170:"ev_eyebrow_2_l",
                #171:"ev_eyebrow_3_l",
                172:"ev_forehead_r",
                173:"ev_forehead",
                174:"ev_forehead_l",
                177:"ev_teeth_upper",
                178:"ev_teeth_lower",
                180:"eyebrow_01_r",
                181:"eyebrow_02_r",
                182:"eyebrow_01_l",
                183:"eyebrow_02_l",
                184:"eyelid_lower_r",
                185:"eyelid_lower_l",
                186:"cheek_upper_r",
                187:"cheek_upper_l",
                188:"cheek_upper_outer_r",
                189:"cheek_upper_outer_l",
                190:"nose_r",
                191:"nose_l",
                192:"lip_corner_r",
                193:"lip_upper_r",
                194:"lip_upper",
                195:"lip_upper_l",
                196:"lip_corner_l",
                197:"lip_outer_lower_l",
                198:"lip_lower",
                199:"lip_lower_l",
                200:"cheek_lower_r",
                201:"cheek_lower_l"
}

def rename_bones(armature):
    pose_bones = armature.pose.bones
    parent_blender_object = armature.parent
    saved_mod = Mod156(file_path=BytesIO(parent_blender_object.albam_imported_item.data))
    bones_array = saved_mod.bones_array
    i = 0
    for b in bones_array:
        if bone_mapping.get(b.anim_map_index):
            name = (bone_mapping.get(b.anim_map_index))
            if i == 0:
                x, y, z = pose_bones[i].head
                if (x, y, z) == (0, 0, 0):#if exist ground root bone
                    name = "root_ground"
            pose_bones[i].name = name
        i += 1